stages:
  - fetch-main
  - check-infra
  - create-infra
  - commit-state
  - destroy-infra

variables:
  ENV_DIR: "environments/dev_m"
  TF_APPROVE: "auto-approve"
  TF_INPUT: "false"
  env: "dev_m.tfvars"

fetch-tfstate:
  stage: fetch-main
  script:
    - echo "Fetching .tfstate from main branch..."
    - git fetch origin main || echo "No state branch yet"
    - git checkout main -- $ENV_DIR/terraform.tfstate || echo "No previous tfstate"
    - git checkout main -- $ENV_DIR/terraform.tfstate.backup || echo "No previous backup"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

check-infra:
  stage: check-infra
  script:
    - echo "Checking for infrastructure state..."
    - cd $ENV_DIR
    - terraform refresh -var-file="dev_m.tfvars" -input=$TF_INPUT || echo "Refresh failed"
    - |
      if [ -f "terraform.tfstate" ]; then
        RESOURCE_COUNT=$(terraform state list 2>/dev/null | wc -l)
        echo "Resource count: $RESOURCE_COUNT"
        if [ "$RESOURCE_COUNT" -gt 0 ]; then
          echo "Infrastructure exists. Skipping apply."
          touch infra_exists.flag
        else
          echo "No infrastructure found. Proceeding to create."
        fi
      else
        echo "No terraform.tfstate found. Proceeding to create."
      fi

  artifacts:
    paths:
      - $ENV_DIR/infra_exists.flag
    expire_in: 1 hour

create-infra:
  stage: create-infra
  needs: [check-infra]
  script:
    - |
      if [ -f $ENV_DIR/infra_exists.flag ]; then
        echo "Infra already exists. Skipping apply."
        exit 0
      fi
    - cd $ENV_DIR
    - terraform apply -$TF_APPROVE -input=$TF_INPUT -var-file="dev_m.tfvars" 
    - terraform output -json > $ENV_DIR/dev_m.json
  artifacts:
    paths:
      - $ENV_DIR/terraform.tfstate
      - $ENV_DIR/terraform.tfstate.backup
      - $ENV_DIR/dev_m.json
    expire_in: 2 hours

commit-state:
  stage: commit-state
  needs: [create-infra]
  script:
    - echo "Committing updated tfstate to state branch..."
    - git config user.email "paragdubey007@gmail.com"
    - git config user.name "dubeyp"
    - git remote set-url origin "http://dubeyp:glpat-***REDACTED***@gitlab.local/dubeyp/globalconfig.git"
    - git fetch  origin main 
    - git checkout main || git checkout -b main
    - cp $ENV_DIR/terraform.tfstate .
    - cp $ENV_DIR/terraform.tfstate.backup .
    - cp $ENV_DIR/$env.json
    - git add $ENV_DIR/terraform.tfstate $ENV_DIR/terraform.tfstate.backup $ENV_DIR/dev_m.json
    - git commit -m "Update tfstate for dev_s [ci skip]" || echo "No changes to commit"
    - git pull --rebase origin main
    - git push origin main
  only:
    - main

destroy-infra:
  stage: destroy-infra
  script:
    - cd $ENV_DIR
    - terraform destroy -$TF_APPROVE -input=$TF_INPUT -var-file="dev_m.tfvars" 
  when: manual