stages:
  - fetch-main
  - check-infra
  - create-infra
  - generate-yml
  - commit-state
  - compare-config
  - install-hauler
  - copy-certificate
  - install-rke2
  - install-haproxy
  - install-mariadb
  - destroy-infra

variables:
  ENV_DIR: "environments/dev_s"
  TF_APPROVE: "auto-approve"
  TF_INPUT: "false"
  TF_env: "dev_s.tfvars"
  COMPARE_ENV: dev_s
  ANSIBLE_ENV: "dev-s.yml"
  EXPECTED_RESOURCE_COUNT: "5"

fetch-tfstate:
  stage: fetch-main
  variables:
    GIT_STRATEGY: fetch
  script:
    - echo "Fetching .tfstate from main branch..."
    - git fetch origin main || echo "No state branch yet"
    - git checkout main -- $ENV_DIR/terraform.tfstate || echo "No previous tfstate"
    - git checkout main -- $ENV_DIR/terraform.tfstate.backup || echo "No previous backup"
    # - git checkout main -- $ENV_DIR/inventory.yml
  only:
    - 'triggers'

check-infra:
  stage: check-infra
  script:
    - echo "Checking for infrastructure state..."
    - git checkout main -- $ENV_DIR/terraform.tfstate 
    - cd $ENV_DIR
    - terraform refresh -var-file=$TF_env -input=$TF_INPUT || echo "Refresh failed"
    - |
      if [ -f "terraform.tfstate" ]; then
        RESOURCE_COUNT=$(terraform state list 2>/dev/null | wc -l)
        echo "Resource count: $RESOURCE_COUNT (expected:$EXPECTED_RESOURCE_COUNT)"
        if [ "$RESOURCE_COUNT" -ge "$EXPECTED_RESOURCE_COUNT" ]; then
          echo "Infrastructure exists. Skipping apply."
          touch infra_exists.flag
          terraform output -json > output.json
        else
          echo "No infrastructure found. Proceeding to create."
        fi
      else
        echo "No terraform.tfstate found. Proceeding to create."
      fi
  only:
    - 'triggers'


  artifacts:
    paths:
      - $ENV_DIR/infra_exists.flag
      - $ENV_DIR/output.json
    expire_in: 1 hour

create-infra:
  stage: create-infra
  needs: [check-infra]
  script:
    - |
      if [ -f $ENV_DIR/infra_exists.flag ]; then
        echo "Infra already exists. Skipping apply."
        exit 0
      fi
    - cd $ENV_DIR
    - terraform apply -$TF_APPROVE -input=$TF_INPUT -var-file=$TF_env 
    - terraform output -json > output.json
  artifacts:
    paths:
      - $ENV_DIR/terraform.tfstate
      - $ENV_DIR/terraform.tfstate.backup
      - $ENV_DIR/output.json
    expire_in: 2 hours
  only:
    - 'triggers'
  


generate-yml:
  stage: generate-yml
  needs: [create-infra]
  script:
    - python3 environments/json_to_ini.py $ENV_DIR/output.json $ENV_DIR/inventory.yml
  artifacts:
    paths:
      - $ENV_DIR/inventory.yml
  only:
    - 'triggers'




commit-state:
  stage: commit-state
  needs: 
    - job: create-infra
      artifacts: true
    - job: generate-yml
      artifacts: true  
  script:
    - echo "Committing updated tfstate to state branch..."
    - git config user.email "paragdubey007@gmail.com"
    - git config user.name "dubeyp"
    - git remote set-url origin "http://dubeyp:glpat-***REDACTED***@gitlab.local/dubeyp/globalconfig.git"
    - git fetch origin main 
    - git checkout -f main || git checkout -b main
    - cp $ENV_DIR/terraform.tfstate .
    - cp $ENV_DIR/terraform.tfstate.backup .
    - cp $ENV_DIR/inventory.yml .
    - git add $ENV_DIR/terraform.tfstate $ENV_DIR/terraform.tfstate.backup $ENV_DIR/inventory.yml 
    - git commit -m "Update tfstate for dev_m [ci skip]" || echo "No changes to commit"
    - git pull --no-rebase origin main
    - git push origin main
  only:
    - 'triggers'


compare-config:
  stage: compare-config
  needs: [commit-state]
  script:
    - python3 compareini_yml.py --env $COMPARE_ENV
  artifacts:
    when: always
    paths: 
      - comparison_logs/
  only:
    - 'triggers'

install-hauler:
  stage: install-hauler
  needs: [compare-config]
  script:
    - echo "now installing different components on the vm's"
    - |
      ssh -o StrictHostKeyChecking=no root@192.168.236.32 <<EOSSH
      ssh -o StrictHostKeyChecking=no ansible@172.19.0.30 <<EOF
        set -ex
        cd /home/ansible/ansible/hauler-registry-fileserver-setup-main
        echo "installing hauler"
        ansible-playbook playbooks/site.yml
      EOF
  only:
    - 'triggers'

copy-certificate:
  stage: copy-certificate
  needs: [install-hauler]
  script:
    - echo "copying certificate"
    - |
      ssh -o StrictHostKeyChecking=no root@192.168.236.32 <<EOSSH
      ssh -o StrictHostKeyChecking=no ansible@172.19.0.30 <<EOF
        set -e
        CA_SRC="/home/ansible/ansible/hauler-registry-fileserver-setup-main/CA-certs/ca.crt"
        DESTINATIONS=(
          "/home/ansible/ansible/rke2-airgapped-deployment-hauler-main/cert/ca.crt"
          "/home/ansible/ansible/haproxy-hauler-playbook-main/cert/ca.crt"
          "/home/ansible/ansible/mariadb-hauler-community-main/cert/ca.crt"
        )
        for dest in "${DESTINATIONS[@]}"; do 
          cp -f "\$CA_SRC" "\$dest"
        done 
      EOF
  only:
    - 'triggers'
      
  


install-rke2:
  stage: install-rke2
  needs: [copy-certificate]
  script:
    - echo "now installing different components on the vm's"
    - |
      ssh -o StrictHostKeyChecking=no root@192.168.236.32 <<EOSSH
      ssh -o StrictHostKeyChecking=no ansible@172.19.0.30 <<EOF
        set -ex
        cd /home/ansible/ansible/rke2-airgapped-deployment-hauler-main
        echo "installing rke2"
        ansible-playbook -i inventories/$ANSIBLE_ENV playbooks/site.yml
      EOF
  only:
    - 'triggers'

 

install-haproxy:
  stage: install-haproxy
  needs: [copy-certificate]
  script:
    - echo "now installing different components on the vm's"
    - |
      ssh -o StrictHostKeyChecking=no root@192.168.236.32 <<EOSSH
      ssh -o StrictHostKeyChecking=no ansible@172.19.0.30 <<EOF
        set -ex
        cd /home/ansible/ansible/haproxy-hauler-playbook-main
        echo "installing haproxy"
        ansible-playbook -i inventories/$ANSIBLE_ENV playbooks/haproxy.yml
      EOF
  only:
    - 'triggers'

  

install-mariadb:
  stage: install-mariadb
  needs: [copy-certificate]
  script:
    - echo "now installing different components on the vm's"
    - |
      ssh -o StrictHostKeyChecking=no root@192.168.236.32 <<EOSSH
      ssh -o StrictHostKeyChecking=no ansible@172.19.0.30 <<EOF
        set -ex
        cd /home/ansible/ansible/mariadb-hauler-community-main
        echo "installing mariadb"
        ansible-playbook -i inventories/$ANSIBLE_ENV playbooks/site.yml
      EOF
  only:
    - 'triggers'

 

destroy-infra:
  stage: destroy-infra
  script:
    - cd $ENV_DIR
    - terraform destroy -$TF_APPROVE -input=$TF_INPUT -var-file=$TF_env
  when: manual
  only:
    - 'triggers'
