stages:
  - check-infra
  - create-infra
  - generate-yml
  - compare-config
  - install-hauler
  - copy-certificate
  - install-rke2
  - install-haproxy
  - install-mariadb
  - destroy-infra

variables:
  ENV_DIR: "environments/dev_s"
  TF_APPROVE: "auto-approve"
  TF_INPUT: "false"
  TF_env: "dev_s.tfvars"
  COMPARE_ENV: dev_s
  ANSIBLE_ENV: "dev-s.yml"
  STATE_NAME: "infra-$COMPARE_ENV"
  GITLAB_HOST: "http://gitlab.local"
  CI_PROJECT_ID: "590"
  CI_JOB_TOKEN: "glpat-***REDACTED***"
  CI_USERNAME: "dubeyp"
  


check-infra:
  stage: check-infra
  script:
    - export TF_CLI_CONFIG_FILE="$ENV_DIR/terraform.rc"
    - |
      cat > "$TF_CLI_CONFIG_FILE" <<'RC'
      provider_installation {
       filesystem_mirror {
        path    = "terraform-providers"
        include = ["registry.terraform.io/*/*"]
       }
       direct {
        exclude = ["registry.terraform.io/*/*"]   # block 
       }
      }
      RC

    - echo "Init remote backend (GitLab) and check changes via plan…"
    - export TF_ADDRESS="$GITLAB_HOST/api/v4/projects/$CI_PROJECT_ID/terraform/state/$STATE_NAME"
    # - cd $ENV_DIR
    - |
      terraform -chdir="$ENV_DIR" init -reconfigure \
        -backend-config=address="$TF_ADDRESS" \
        -backend-config=lock_address="$TF_ADDRESS/lock" \
        -backend-config=unlock_address="$TF_ADDRESS/lock" \
        -backend-config=lock_method=POST \
        -backend-config=unlock_method=DELETE \
        -backend-config=retry_wait_min=5 \
        -backend-config=username="$CI_USERNAME" \
        -backend-config=password="$CI_JOB_TOKEN" \
        -input=false
    - terraform -chdir="$ENV_DIR" refresh -var-file="$TF_env" -input="$TF_INPUT" || echo "Refresh failed"
    
    - |
      set +e
      terraform -chdir="$ENV_DIR" plan -var-file="$TF_env" -input=false -detailed-exitcode -out=tf.plan
      PLAN_EXIT_CODE=$?
      set -e
  
      if [ "$PLAN_EXIT_CODE" -eq 0 ]; then
        echo "No changes needed - infra up to date"
        touch "$ENV_DIR/infra_exists.flag"
        terraform -chdir="$ENV_DIR" output -json > "$ENV_DIR/output.json"
      elif [ "$PLAN_EXIT_CODE" -eq 2 ]; then
        echo "Changes detected - infra will be created/updated"
        
      else
        echo "Plan failed"; exit 1
      fi

  only:
    - 'triggers'
  artifacts:
    paths:
      - $ENV_DIR/infra_exists.flag
      - $ENV_DIR/output.json
      - $ENV_DIR/tf.plan
    reports:
      dotenv: plan.env
    expire_in: 1 hour


create-infra:
  stage: create-infra
  needs: [check-infra]
  script:
    - export TF_CLI_CONFIG_FILE="$ENV_DIR/terraform.rc"
    - |
      cat > "$TF_CLI_CONFIG_FILE" <<'RC'
      provider_installation {
       filesystem_mirror {
        path    = "terraform-providers"
        include = ["registry.terraform.io/*/*"]
       }
       direct {
        exclude = ["registry.terraform.io/*/*"]   
       }
      }
      RC
    - export TF_ADDRESS="$GITLAB_HOST/api/v4/projects/$CI_PROJECT_ID/terraform/state/$STATE_NAME"
    # - cd $ENV_DIR
    - |
      terraform -chdir="$ENV_DIR" init -reconfigure \
        -backend-config=address="$TF_ADDRESS" \
        -backend-config=lock_address="$TF_ADDRESS/lock" \
        -backend-config=unlock_address="$TF_ADDRESS/lock" \
        -backend-config=lock_method=POST \
        -backend-config=unlock_method=DELETE \
        -backend-config=retry_wait_min=5 \
        -backend-config=username="$CI_USERNAME" \
        -backend-config=password="$CI_JOB_TOKEN" \
        -input=false
    - |
      if [ -f "$ENV_DIR/infra_exists.flag" ]; then
        echo "Infrastructure already exists and is up to date - skipping apply"
        
      elif [ -f "$ENV_DIR/tfplan" ]; then
        echo "Applying pre-generated plan..."
        terraform apply -input=false tfplan
        terraform  output -json > output.json
      else
        echo " No plan file found, generating and applying..."
        terraform -chdir="$ENV_DIR" apply -var-file="$TF_env" -auto-approve -input=false
        terraform output -json > output.json
      fi
  artifacts:
    paths:
      - $ENV_DIR/output.json
    expire_in: 2 hours
  only:
    - 'triggers'
  
generate-yml:
  stage: generate-yml
  # needs: [create-infra]
  script:
    - python3 environments/json_to_ini.py $ENV_DIR/output.json $ENV_DIR/inventory.yml
  artifacts:
    paths:
      - $ENV_DIR/inventory.yml
  only:
    - 'triggers'

compare-config:
  stage: compare-config
  script:
    - python3 compareini_yml.py --env dev_s
  artifacts:
    when: always
    paths: 
      - comparison_logs/
  only:
    - 'triggers'

install-hauler:
  stage: install-hauler
  needs: [compare-config]
  script:
    - echo "now installing different components on the vm's"
    - |
      ssh -o StrictHostKeyChecking=no root@gitlab.local <<EOSSH
      ssh -o StrictHostKeyChecking=no ansible@priv-172-19-0-30.local <<EOF
        set -ex
        cd /home/ansible/ansible/hauler-registry-fileserver-setup-main
        if [[ ! -f "/home/ansible/ansible/hauler-registry-fileserver-setup-main/flags/hauler_installed.flag" ]]; then
          echo "installing hauler"
          ansible-playbook playbooks/site.yml
          mkdir -p /home/ansible/ansible/hauler-registry-fileserver-setup-main/flags/
          touch /home/ansible/ansible/hauler-registry-fileserver-setup-main/flags/hauler_installed.flag
        else
          echo "hauler already installed"
        fi
      EOF
  
  only:
    - 'triggers'

copy-certificate:
  stage: copy-certificate
  needs: [install-hauler]
  script:
    - echo "copying certificate"
    - |
      ssh -o StrictHostKeyChecking=no root@gitlab.local <<'EOSSH'
      ssh -o StrictHostKeyChecking=no ansible@priv-172-19-0-30.local <<'EOF'
        set -ex
        cd /home/ansible/ansible/hauler-registry-fileserver-setup-main/CA-Certs
        cp -f ca.crt /home/ansible/ansible/rke2-airgapped-deployment-hauler-main/cert
        cp -f ca.crt /home/ansible/ansible/haproxy-hauler-playbook-main/cert
        cp -f ca.crt /home/ansible/ansible/mariadb-hauler-community-main/cert
      EOF
  
  only:
    - 'triggers'
        
      
      
  


install-rke2:
  stage: install-rke2
  needs: [copy-certificate]
  script:
    - echo "now installing different components on the vm's"
    - |
      ssh -o StrictHostKeyChecking=no root@gitlab.local <<EOSSH
      ssh -o StrictHostKeyChecking=no ansible@priv-172-19-0-30.local <<EOF
        set -ex
        cd /home/ansible/ansible/rke2-airgapped-deployment-hauler-main
        if [[ ! -f "/home/ansible/ansible/rke2-airgapped-deployment-hauler-main/flags/rke2_installed.flag" ]]; then
          echo "installing rke2"
          ansible-playbook -i inventories/$ANSIBLE_ENV playbooks/site.yml
          mkdir -p /home/ansible/ansible/rke2-airgapped-deployment-hauler-main/flags/
          touch /home/ansible/ansible/rke2-airgapped-deployment-hauler-main/flags/rke2_installed.flag
        else
          echo "rke2 already installed"
        fi
      EOF
  
  only:
    - 'triggers'

 

install-haproxy:
  stage: install-haproxy
  needs: [copy-certificate]
  script:
    - echo "now installing different components on the vm's"
    - |
      ssh -o StrictHostKeyChecking=no root@gitlab.local <<EOSSH
      ssh -o StrictHostKeyChecking=no ansible@priv-172-19-0-30.local <<EOF
        set -ex
        cd /home/ansible/ansible/haproxy-hauler-playbook-main
        if [[ ! -f "/home/ansible/ansible/haproxy-hauler-playbook-main/flags/haproxy_installed.flag" ]]; then
          echo "installing haproxy"
          ansible-playbook -i inventories/$ANSIBLE_ENV playbooks/haproxy.yml
          mkdir -p /home/ansible/ansible/haproxy-hauler-playbook-main/flags/
          touch /home/ansible/ansible/haproxy-hauler-playbook-main/flags/haproxy_installed.flag
        else
          echo "haproxy already installed"
        fi      
      EOF
  
  only:
    - 'triggers'

  

install-mariadb:
  stage: install-mariadb
  needs: [copy-certificate]
  script:
    - echo "now installing different components on the vm's"
    - |
      ssh -o StrictHostKeyChecking=no root@gitlab.local <<EOSSH
      ssh -o StrictHostKeyChecking=no ansible@priv-172-19-0-30.local <<EOF
        set -ex
        cd /home/ansible/ansible/mariadb-hauler-community-main
        if [[ ! -f "/home/ansible/ansible/mariadb-hauler-community-main/flags/mariadb_installed.flag" ]]; then
          echo "installing mariadb"
          ansible-playbook -i inventories/$ANSIBLE_ENV playbooks/site.yml
          mkdir -p /home/ansible/ansible/mariadb-hauler-community-main/flags/
          touch /home/ansible/ansible/mariadb-hauler-community-main/flags/mariadb_installed.flag
        else
          echo "mariadb already installed"
        fi
      EOF
  
  only:
    - 'triggers'

 

destroy-infra:
  stage: destroy-infra
  script:
    - export TF_CLI_CONFIG_FILE="$ENV_DIR/terraform.rc"
    - |
      cat > "$TF_CLI_CONFIG_FILE" <<'RC'
      provider_installation {
       filesystem_mirror {
        path    = "terraform-providers"
        include = ["registry.terraform.io/*/*"]
       }
       direct {
        exclude = ["registry.terraform.io/*/*"]   
       }
      }
      RC
    - export TF_ADDRESS="$GITLAB_HOST/api/v4/projects/$CI_PROJECT_ID/terraform/state/$STATE_NAME"
    - |
      terraform -chdir="$ENV_DIR" init -reconfigure \
        -backend-config=address="$TF_ADDRESS" \
        -backend-config=lock_address="$TF_ADDRESS/lock" \
        -backend-config=unlock_address="$TF_ADDRESS/lock" \
        -backend-config=lock_method=POST \
        -backend-config=unlock_method=DELETE \
        -backend-config=retry_wait_min=5 \
        -backend-config=username="dubeyp" \
        -backend-config=password="$CI_JOB_TOKEN" \
        -input=false
    - terraform -chdir="$ENV_DIR" destroy -$TF_APPROVE -input=$TF_INPUT -var-file=$TF_env
    - |
      ssh -o StrictHostKeyChecking=no root@gitlab.local <<'EOSSH'
      ssh -o StrictHostKeyChecking=no ansible@priv-172-19-0-30.local <<'EOF'
        rm -f /home/ansible/ansible/hauler-registry-fileserver-setup-main/flags/hauler_installed.flag
        rm -f /home/ansible/ansible/rke2-airgapped-deployment-hauler-main/flags/rke2_installed.flag
        rm -f /home/ansible/ansible/haproxy-hauler-playbook-main/flags/haproxy_installed.flag
        rm -f /home/ansible/ansible/mariadb-hauler-community-main/flags/mariadb_installed.flag
      EOF
  when: manual
  only:
    - 'triggers'
